### ISSUE TITLE
Using zsh in cygwin shows bash prompt and does not load `.zshrc`

### ISSUE THREAD

**Issue by papanito** [romkatv/zsh-bin#17]
On work I have to use windows and cygwin. On my dev-machine I can use zsh perfectly fine, however on some other servers, when I start zsh I get the "bash" prompt

```shell
\[\033[35m\]\t\[\033[m\]-\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h: \[\033[33;1m\]\w\[\033[m\]\n>                                                   $(git_super_status)
```

Sourcing my `~\.zshrc` also does nothing.

I installed it as follows:

```shell
sh -c "$(curl -fskSL https://git.intra/users/papanito/repos/zsh-bin/raw/install?at=refs%2Fheads%2Fmaster)"
Choose installation directory for Zsh 5.8:

  (1)  /usr/local        <= does not need sudo
  (2)  ~/.local          <= does not need sudo
  (3)  Custom directory.
  (q)  Quit and do nothing.

Choice [123q]: 2

===> installing Zsh 5.8 to /c/Users/SC146082AS/.local
===> fetching zsh-5.8-msys_nt-10.0-x86_64.tar.gz
===> verifying archive integrity
===> sha256 signature matches
===> md5 signature matches
===> extracting files
Installed Zsh 5.8 to /c/Users/papanito/.local

To start Zsh, type:

  zsh
````

I run `zsh` from within a `git-bash`:

```
bash --version
GNU bash, version 5.2.15(1)-release (x86_64-pc-msys)
```

```shell
which zsh
/c/Users/papanito/.local/bin/zsh
```

**Comment by romkatv** [comment]
Zsh sources user startup files from `$ZDOTDIR`, or from `$HOME` if `ZDOTDIR` is not set. You can verify that it works by running the following command in zsh:

```zsh
printf '\necho "hello from .zshrc"\n' >>${ZDOTDIR:-$HOME}/.zshrc && zsh -ic ''
```

This should print "hello from .zshrc". If it does not, run `zsh --sourcetrace -ic ''` for clues.

You can also run this command from bash. If it does not result in "hello from .zshrc", one possible reason is that `$HOME` under bash isn't the same as under zsh. I don't use cygwin (virtually nobody does these days because WSL exists), so I cannot say whether this is normal or even possible.

**Comment by papanito** [comment]
Thanks for your answer.

> This should print "hello from .zshrc"

Yes that works fine

> virtually nobody does these days because WSL exists

I would be happy to use WSL instead, it would make things so much easier. Unfortunately I can't as these Windows Servers do not have WSL.

> $HOME under bash isn't the same as under zsh

Looks also as expected.

Will go ahead and close the issue again, probably more related to cygwin rather zsh binary
