### ISSUE TITLE
[BUG] Can't find terminal definition error

### ISSUE THREAD

**Issue by m33mt33n** [romkatv/zsh-bin#18]

**Comment by m33mt33n** [comment]
hello romkstv,

I tried installation of zsh using prebuilt version using archive
`zsh-5.8-linux-armv7l.tar.gz`, but it did not worked as expected and failed
with error `can't find terminal definitions`, although all paths set by
relocate scripts are looking fine (verified with strings command), but it
got failed in finding terminfo (AFAIK), any solution?

thanks
Moin
[sorry, there was something wrong with my browser so message were posted without body, but why you closed the issue?]

**Comment by romkatv** [comment]
I've never seen that error. I don't know what might have caused it. If you ever find out, please post a comment here.

**Comment by m33mt33n** [comment]
OK,

thanks for your reply, issue is similar to issue #12 `backspace is producing space character`
and I believe that failure in finding termino is the cause.

thanks again and regards
Moin

**Comment by sputnick1124** [comment]
@m33mt33n I ran into this issue today, but only because I naively tried simply download and unpacking the tar release manually (before I realized that there were installation instructions 🙄 ).

That said, before I realized that I was doing things wrong, I grepped the output of an `strace` log of my improper installation ofr `terminfo` and found all the places it was trying to find terminal definitions. You could try the same to see where `zsh` is looking for terminfo, and why it's not finding it.
